const Images = {
  Completed: require('../../assets/icons/completed.png'),
  PasswordChanged: require('../../assets/icons/passwordChanged.png'),
  FavouriteHeart: require('../../assets/icons/heartFavourite.png'),
  HeartActive: require('../../assets/icons/Heart-1.png'),
  // HeartInActive: require('../../assets/icons/Heart.png'),
  Crown: require('../../assets/icons/premium.png'),
  CompleteClass: require('../../assets/icons/completeClasses.png'),
  Help: require('../../assets/icons/question.png'),
  TermsAndCond: require('../../assets/icons/terms.png'),
  LogoutIcon: require('../../assets/icons/Logout-Outline.png'),
  ChangePassword: require('../../assets/icons/changepassword.png'),
  CrownNoBg: require('../../assets/icons/crownNoBg.png'),
  DiamondCircle: require('../../assets/icons/diamondCircle.png'),
  Cross: require('../../assets/icons/cross.png'),
  // TestingImage: require('../../assets/images/testingMockupImage.png'),
  PlayBtn: require('../../assets/icons/playBtn.png'),
  MicBtn: require('../../assets/icons/mic.png'),
  // TestingAvatar: require('../../assets/images/testingAvatar.png'),
  MicOpenBtn: require('../../assets/icons/micOpenCirlce.png'),
  SpeakerBtn: require('../../assets/icons/speakerBtn.png'),
  // TestingAvatar2: require('../../assets/images/TestingAvatar2.png'),
  HeartCircle: require('../../assets/icons/heartCircle.png'),
  HeartCircleFilled: require('../../assets/icons/filledCircleHeart.png'),
  TermCircle: require('../../assets/icons/termcircle.png'),
  CameraCircle: require('../../assets/icons/cameraCircle.png'),
  TryAgainCircle: require('../../assets/icons/tryAgainCircel.png'),
  Advance: require('../../assets/icons/advance.png'),
  Intermediate: require('../../assets/icons/intermediate.png'),
  Beginner: require('../../assets/icons/beginner.png'),
  Work: require('../../assets/icons/work.png'),
  DailyLife: require('../../assets/icons/dailyLife.png'),
  Travel: require('../../assets/icons/travel.png'),
  Education: require('../../assets/icons/education.png'),
  CircleCheck: require('../../assets/icons/circleCheck.png'),
  CircleX: require('../../assets/icons/circleX.png'),
  UserPlaceholder: require('../../assets/icons/userPlaceholder.png'),
  EnabledSubtitle: require('../../assets/icons/EnableSubtitles.png'),
  EmptyState: require('../../assets/images/emptyState.png'),
  NoDataFound: require('../../assets/images/noDataFound.png'),
  Clue: require('../../assets/icons/clue.png'),

  // New Images
  GoogleLogo: require('../../assets/icons/google.png'),
  user1: require('../../assets/icons/user1.png'),
  user2: require('../../assets/icons/user2.png'),
  mail: require('../../assets/icons/mail.png'),
  smartphone: require('../../assets/icons/smartphone.png'),
  Search: require('../../assets/icons/Search.png'),

  OnBoard1: require('../../assets/images/Onboarding1.png'), //Ner
  OnBoard2: require('../../assets/images/Onboarding2.png'), //New
  OnBoard3: require('../../assets/images/Onboarding3.png'), //New
  OnBoard4: require('../../assets/images/Onboarding4.png'), //New

  HomeActive: require('../../assets/icons/homeFilled.png'),
  HomeInActive: require('../../assets/icons/Home.png'),
  ProfileActive: require('../../assets/icons/profile-circle1.png'),
  ProfileInActive: require('../../assets/icons/profile-circle.png'),
  SearchInActive: require('../../assets/icons/SearchInActive.png'),
  SearchActive: require('../../assets/icons/Search.png'),
  BellInActive: require('../../assets/icons/bell.png'),
  BellActive: require('../../assets/icons/bellActive.png'),
  CourseInActive: require('../../assets/icons/CoursesInActive.png'),
  CourseActive: require('../../assets/icons/CoursesActive.png'),
  Logo: require('../../assets/icons/logo.png'),
  EyeAbleIcon: require('../../assets/icons/eye_able.png'),
  EyeDisableIcon: require('../../assets/icons/eyeClose.png'),
  Wow: require('../../assets/icons/wow.png'),
  BackBtn: require('../../assets/icons/arrowleft.png'),
  ArrowDown: require('../../assets/icons/arrowdown.png'),
  HeartFilled: require('../../assets/icons/heartFilled.png'),
  HeartEmpty: require('../../assets/icons/heartEmpty.png'),
  Star: require('../../assets/icons/star.png'),

  Drawer: require('../../assets/icons/Drawer.png'),
  About: require('../../assets/icons/About.png'),
  Coins: require('../../assets/icons/coins.png'),
  Invitation: require('../../assets/icons/paper-plane.png'),
  Common: require('../../assets/icons/Comman.png'),
  TermCondition: require('../../assets/icons/Term&Condition.png'),
  PrivacyPilicy: require('../../assets/icons/privacy-policy.png'),
  HelpCenter: require('../../assets/icons/HelpCenter.png'),
  Certificate: require('../../assets/icons/certificate.png'),
  Stroke: require('../../assets/icons/Stroke.png'),
  Arrow: require('../../assets/icons/Arrow.png'),
  LogOut: require('../../assets/icons/LogOut.png'),
  ArrowChevron: require('../../assets/icons/ArrowChevron.png'),
  Placeholder: require('../../assets/icons/Placeholder.png'),
  Transactions: require('../../assets/icons/Transactions.png'),

  // Add New
  Signup: require('../../assets/icons/signup.png'),
  Back: require('../../assets/icons/back.png'),
  Contacts: require('../../assets/icons/contacts.png'),
  People: require('../../assets/icons/people.png'),
  Plus: require('../../assets/icons/plus.png'),
  Whatsapp: require('../../assets/icons/whatsapp.png'),
  Sms: require('../../assets/icons/messages.png'),
  Messenger: require('../../assets/icons/messenger.png'),
  Insta: require('../../assets/icons/insta.png'),
  Preference: require('../../assets/icons/preference.png'),
  Girl: require('../../assets/images/girl.jpg'),
  Edit: require('../../assets/icons/pen.png'),
  Delete: require('../../assets/icons/bin.png'),
  Phonebook: require('../../assets/icons/phone-book.png'),
  SettingsActive: require('../../assets/icons/settingsFilled.png'),
  SettingsInactive: require('../../assets/icons/settings.png'),
  Dashboard: require('../../assets/icons/dashboard.png'),
  Out: require('../../assets/icons/out.png'),
  Profile: require('../../assets/icons/profile.png'),
  Location: require('../../assets/icons/location.png'),
  Map: require('../../assets/icons/map.png'),
  DualCam: require('../../assets/icons/dualCam.png'),
  FlashOn: require('../../assets/icons/flash-on.png'),
  FlashOff: require('../../assets/icons/flash-off.png'),
  Bell: require('../../assets/icons/bell.png'),
  Info: require('../../assets/icons/i.png'),
  Layers: require('../../assets/icons/layers.png'),
  Eye: require('../../assets/icons/eye.png'),
  Target: require('../../assets/icons/target.png'),
  Pin: require('../../assets/icons/pin.png'),
  Marker: require('../../assets/icons/marker.png'),
  Searching: require('../../assets/icons/searching.png'),
  SafeWord: require('../../assets/icons/speaking.png'),
  Incident: require('../../assets/icons/warning.png'),
  Blur: require('../../assets/icons/blur.png'),

  Camera: require('../../assets/icons/camera.png'),
  EndCall: require('../../assets/icons/endCall.png'),
  Mic: require('../../assets/icons/mute.png'),
};

export default Images;
