const Images = {
  // New MuslimLynk Icons & Images
  Logo: require('../../assets/icons/logo.png'),
  GoogleLogo: require('../../assets/icons/google.png'),
  BackBtn: require('../../assets/icons/arrowleft.png'),
  Arrow: require('../../assets/icons/Arrow.png'),
  Search: require('../../assets/icons/Search.png'),
  FavouriteHeart: require('../../assets/icons/heartFavourite.png'),
  TestingAvatar: require('../../assets/images/testingAvatar.png'),
  HeartFilled: require('../../assets/icons/heartFilled.png'),
  HeartEmpty: require('../../assets/icons/heartEmpty.png'),
  EyeDisableIcon: require('../../assets/icons/eyeClose.png'),
  EyeAbleIcon: require('../../assets/icons/eye_able.png'),
  Cross: require('../../assets/icons/cross.png'),
  EmptyState: require('../../assets/images/emptyState.png'),
  UserPlaceholder: require('../../assets/icons/userPlaceholder.png'),
  CircleCheck: require('../../assets/icons/circleCheck.png'),
  CircleX: require('../../assets/icons/circleX.png'),
  PlayBtn: require('../../assets/icons/playBtn.png'),
  Wow: require('../../assets/icons/wow.png'),
  ProfileInActive: require('../../assets/icons/profile-circle.png'),
  About: require('../../assets/icons/About.png'),
  TermCondition: require('../../assets/icons/Term&Condition.png'),
  PrivacyPilicy: require('../../assets/icons/privacy-policy.png'),
  LogOut: require('../../assets/icons/LogOut.png'),
  Delete: require('../../assets/icons/bin.png'),
  Stroke: require('../../assets/icons/Stroke.png'),
  Drawer: require('../../assets/icons/Drawer.png'),
  HomeActive: require('../../assets/icons/Home.png'),
  FAQ: require('../../assets/icons/faq.png'),
  CourseActive: require('../../assets/icons/CoursesActive.png'),
  KodeReach: require('../../assets/images/kodereach.jpg'),
  Chat: require('../../assets/icons/chat.png'),
  View: require('../../assets/icons/view.png'),
  LinkedIn: require('../../assets/icons/linkedin.png'),
  Location: require('../../assets/icons/location.png'),
  Filter: require('../../assets/icons/filter.png'),
  Send: require('../../assets/icons/send.png'),
};

export default Images;
